version: '3.8'

volumes:
  database:

services:
  db:
    image: "mariadb:latest"
    restart: unless-stopped
    env_file: [ .env ]
    #ports:
    #  - "3306:3306"
    volumes:
      - database:/var/lib/mysql

  backend:
    build:
      context: E:\dev\quellen\alicegithub\shopping-list-backend
      dockerfile: E:\dev\quellen\alicegithub\shopping-list-backend\Dockerfile
    restart: unless-stopped
    depends_on: [ db ]
    env_file: [ .env ]
    #ports:
    #  - "8080:8080"

  frontend:
    depends_on: [ backend ]
    build:
      context: E:\dev\quellen\alicegithub\shopping-list-frontend
      dockerfile: E:\dev\quellen\alicegithub\shopping-list-frontend\Dockerfile
    restart: unless-stopped
    env_file: [ .env ]
    ports:
      - "8080:80"
